//
//  PPPCViewModel.swift
//  JPs Packager
//
//  Created by James Poole on 18/04/2025.
//

import SwiftUI

class PPPCViewModel: ObservableObject {
    @Published var apps: [AppInfo] = []
    @Published var dropTargeted = false
    @Published var exportOrganization = "JPs Packager"
    @Published var exportName = "PPPC Configuration"
    @Published var exportDescription = "Generated by JPs Packager"
    @AppStorage("logs") var logs: String = ""

    private func timestamp() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        return formatter.string(from: Date())
    }

    @discardableResult
    func addApp(from url: URL) -> AppInfo {
        let bid = getBundleID(from: url)
        let req = getCodeRequirement(from: url)
        let icon = NSWorkspace.shared.icon(forFile: url.path)
        let permissions = pppcServiceDisplayNames
            .keys
            .sorted {
                (pppcServiceDisplayNames[$0] ?? "")
                    < (pppcServiceDisplayNames[$1] ?? "")
            }
            .map { PPPCPermission(service: $0) }
        let info = AppInfo(
            url: url,
            bundleID: bid,
            codeRequirement: req,
            icon: icon,
            permissions: permissions
        )
        if !apps.contains(info) {
            apps.append(info)
        }
        return info
    }

    func remove(app: AppInfo) {
        if let idx = apps.firstIndex(of: app) {
            apps.remove(at: idx)
        }
    }

    func presentAppPicker() {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.application]
        panel.canChooseFiles = true
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = true
        panel.begin { result in
        if result == .OK {
            DispatchQueue.main.async {
                for url in panel.urls {
                    self.addApp(from: url)
                }
            }
        }
        }
    }

    func getBundleID(from url: URL) -> String {
        return Bundle(url: url)?.bundleIdentifier ?? "Unavailable"
    }

    func getCodeRequirement(from url: URL) -> String {
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/usr/bin/codesign")
        task.arguments = ["-dr", "-", url.path]
        let pipe = Pipe()
        task.standardOutput = pipe
        task.standardError = pipe
        do {
            try task.run()
            task.waitUntilExit()
        } catch {
            return "Error running codesign"
        }
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        let output = String(data: data, encoding: .utf8) ?? ""
        if let line = output.components(separatedBy: "\n").first(where: {
            $0.contains("designated =>")
        }) {
            return line.replacingOccurrences(of: "designated =>", with: "")
                .trimmingCharacters(in: .whitespaces)
        } else {
            return "Code requirement not found"
        }
    }

    func appName(for url: URL) -> String {
        return Bundle(url: url)?.object(forInfoDictionaryKey: "CFBundleName")
            as? String ?? url.deletingPathExtension().lastPathComponent
    }

    func handleAppDrop(providers: [NSItemProvider]) -> Bool {
        var handled = false

        for provider in providers {
            if provider.hasItemConformingToTypeIdentifier("public.file-url") {
                _ = provider.loadObject(ofClass: URL.self) { object, _ in
                    guard let url = object, url.pathExtension == "app" else {
                        return
                    }
                    DispatchQueue.main.async {
                        self.addApp(from: url)
                    }
                }
                handled = true
            }
        }

        return handled
    }

    func handleConfigDrop(
        providers: [NSItemProvider],
        setPendingURL: @escaping (URL) -> Void,
        triggerConfirmation: @escaping () -> Void
    ) -> Bool {
        guard let provider = providers.first else { return false }
        _ = provider.loadObject(ofClass: URL.self) { object, _ in
            guard let url = object, url.pathExtension == "mobileconfig" else {
                return
            }
            DispatchQueue.main.async {
                if self.apps.isEmpty {
                    self.importMobileConfig(from: url)
                } else {
                    setPendingURL(url)
                    triggerConfirmation()
                }
            }
        }
        return true
    }

    func exportMobileConfig(identifier: String) {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.init(filenameExtension: "mobileconfig")!]
        panel.nameFieldStringValue = "\(self.exportName).mobileconfig"
        panel.canCreateDirectories = true

        panel.begin { result in
            guard result == .OK, let url = panel.url else { return }

            var payloadContent: [[String: Any]] = []

            for app in self.apps {
                var servicesDict: [String: [[String: Any]]] = [:]

                for permission in app.permissions where permission.auth != .none
                {
                    let entry: [String: Any] = [
                        "Authorization": permission.auth.rawValue,
                        "Identifier": app.bundleID,
                        "IdentifierType": "bundleID",
                        "CodeRequirement": app.codeRequirement,
                        "Comment": permission.comment,
                    ]

                    servicesDict[permission.service, default: []].append(entry)
                }

                let payloadUUID = UUID().uuidString.uppercased()
                let payload: [String: Any] = [
                    "PayloadDescription":
                        "Privacy Preferences Policy Control for \(app.displayName)",
                    "PayloadDisplayName": "\(app.displayName) Permissions",
                    "PayloadIdentifier": UUID().uuidString,
                    "PayloadOrganization": "JPs Packager",
                    "PayloadType": "com.apple.TCC.configuration-profile-policy",
                    "PayloadUUID": payloadUUID,
                    "PayloadVersion": 1,
                    "Services": servicesDict,
                ]

                payloadContent.append(payload)
            }

            let profile: [String: Any] = [
                "PayloadContent": payloadContent,
                "PayloadDescription": self.exportDescription,
                "PayloadDisplayName": self.exportName,
                "PayloadIdentifier": identifier,
                "PayloadOrganization": self.exportOrganization,
                "PayloadScope": "System",
                "PayloadType": "Configuration",
                "PayloadUUID": UUID().uuidString,
                "PayloadVersion": 1,
            ]

            do {
                let data = try PropertyListSerialization.data(
                    fromPropertyList: profile,
                    format: .xml,
                    options: 0
                )
                try data.write(to: url)
            } catch {
                print("Failed to write mobileconfig: \(error)")
            }
        }
    }

    func importMobileConfig(from url: URL) {
        do {
            let data = try Data(contentsOf: url)
            let plist = try PropertyListSerialization.propertyList(
                from: data,
                options: [],
                format: nil
            )

            guard let dict = plist as? [String: Any],
                let payloads = dict["PayloadContent"] as? [[String: Any]]
            else {
                logs +=
                    "[\(timestamp())] ❌ Invalid or missing PayloadContent in \(url.lastPathComponent)\n"
                return
            }

            logs +=
                "[\(timestamp())] ✅ Imported .mobileconfig: \(url.lastPathComponent)\n"

            if let name = dict["PayloadDisplayName"] as? String {
                self.exportName = name
            }

            if let description = dict["PayloadDescription"] as? String {
                self.exportDescription = description
            }

            if let org = dict["PayloadOrganization"] as? String {
                self.exportOrganization = org
            }

            for payload in payloads {
                guard
                    let services = payload["Services"]
                        as? [String: [[String: Any]]]
                else {
                    continue
                }

                for (service, entries) in services {
                    for entry in entries {
                        guard let identifier = entry["Identifier"] as? String,
                            let codeRequirement = entry["CodeRequirement"]
                                as? String,
                            let authString = entry["Authorization"] as? String,
                            let auth = PPPCAuth(rawValue: authString)
                        else { continue }

                        let comment = entry["Comment"] as? String ?? ""

                        DispatchQueue.main.async {
                            if let appURL = NSWorkspace.shared
                                .urlForApplication(
                                    withBundleIdentifier: identifier
                                )
                            {
                                let app =
                                    self.apps.first(where: {
                                        $0.bundleID == identifier
                                    }) ?? self.addApp(from: appURL)
                                if let idx = app.permissions.firstIndex(where: {
                                    $0.service == service
                                }) {
                                    app.permissions[idx].auth = auth
                                    app.permissions[idx].comment = comment
                                }
                            } else {
                                self.logs +=
                                    "[\(self.timestamp())] ⚠️ Could not resolve app with bundle ID: \(identifier)\n"
                                let icon =
                                    NSImage(
                                        systemSymbolName:
                                            "questionmark.square.dashed",
                                        accessibilityDescription: nil
                                    ) ?? NSImage()
                                let permissions = pppcServiceDisplayNames
                                    .keys
                                    .sorted {
                                        (pppcServiceDisplayNames[$0] ?? "")
                                            < (pppcServiceDisplayNames[$1] ?? "")
                                    }
                                    .map { PPPCPermission(service: $0) }

                                let newApp = AppInfo(
                                    url: URL(fileURLWithPath: "/\(identifier)"),
                                    bundleID: identifier,
                                    codeRequirement: codeRequirement,
                                    icon: icon,
                                    permissions: permissions
                                )

                                if let idx = newApp.permissions.firstIndex(
                                    where: { $0.service == service })
                                {
                                    newApp.permissions[idx].auth = auth
                                    newApp.permissions[idx].comment = comment
                                }

                                DispatchQueue.main.async {
                                    if !self.apps.contains(newApp) {
                                        self.apps.append(newApp)
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } catch {
            logs +=
                "[\(timestamp())] ❌ Failed to import \(url.lastPathComponent): \(error.localizedDescription)\n"
        }
    }

}
